//Rafael Duarte Daltio - 2266539
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Jan2 extends javax.swing.JFrame {
    private GerAluno gerAlu = new GerAluno();
    private Aluno alu = new Aluno();
    
    private static Jan2 jan2Unico;
    
    private Jan2() {
        initComponents();
    }
    
    public static Jan2 getJan2(){
        if(jan2Unico == null){
            jan2Unico = new Jan2();
        }
        return jan2Unico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BTCadAluno = new javax.swing.JLabel();
        BTFecJan2 = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        RTNascimento = new javax.swing.JLabel();
        txtNascimento = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        RTEmail = new javax.swing.JLabel();
        txtEscolaridade = new javax.swing.JTextField();
        RTEscolaridade = new javax.swing.JLabel();
        RTCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        txtDIM = new javax.swing.JTextField();
        RTDIM = new javax.swing.JLabel();
        txtDFM = new javax.swing.JTextField();
        RTDFM = new javax.swing.JLabel();
        BTMatricular = new javax.swing.JButton();
        BTConsultarMatricula = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabCadAlu = new javax.swing.JTable();
        RTNome1 = new javax.swing.JLabel();
        BTLimpar = new javax.swing.JButton();
        BTConsultarSala = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BTCadAluno.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BTCadAluno.setText("Cadastro de aluno");

        BTFecJan2.setText("Fechar");
        BTFecJan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTFecJan2ActionPerformed(evt);
            }
        });

        RTNascimento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RTNascimento.setText("Data de nascimento:");

        RTEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RTEmail.setText("Email:");

        RTEscolaridade.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RTEscolaridade.setText("Escolaridade:");

        RTCPF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RTCPF.setText("CPF:");

        RTDIM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RTDIM.setText("Data do início da Matrícula:");

        RTDFM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RTDFM.setText("Data do fim da Matrícula:");

        BTMatricular.setText("Matricular");
        BTMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTMatricularActionPerformed(evt);
            }
        });

        BTConsultarMatricula.setText("Consultar Matrícula");
        BTConsultarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTConsultarMatriculaActionPerformed(evt);
            }
        });

        tabCadAlu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data de nascimento", "Email", "Escolaridade", "CPF", "Data de início da Matrícula", "Data do fim da Matrícula"
            }
        ));
        jScrollPane2.setViewportView(tabCadAlu);

        RTNome1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RTNome1.setText("Nome:");

        BTLimpar.setText("Limpar");
        BTLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTLimparActionPerformed(evt);
            }
        });

        BTConsultarSala.setText("Consultar sala");
        BTConsultarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTConsultarSalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(580, 580, 580)
                .addComponent(BTCadAluno)
                .addGap(0, 558, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RTEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RTEscolaridade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RTDIM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDIM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RTCPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RTNascimento)
                                    .addComponent(RTNome1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RTDFM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDFM, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BTConsultarSala)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTMatricular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BTConsultarMatricula)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTFecJan2, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(BTCadAluno)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RTNome1))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RTNascimento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RTEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RTEscolaridade)
                            .addComponent(txtEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RTCPF)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RTDIM)
                            .addComponent(txtDIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RTDFM)
                            .addComponent(txtDFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTLimpar)
                    .addComponent(BTConsultarMatricula)
                    .addComponent(BTMatricular))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTFecJan2)
                    .addComponent(BTConsultarSala))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTFecJan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTFecJan2ActionPerformed
        dispose();
    }//GEN-LAST:event_BTFecJan2ActionPerformed

    private void BTMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTMatricularActionPerformed
        cadastrar();
        listarTabela();
        limpar();
    }//GEN-LAST:event_BTMatricularActionPerformed

    private void BTConsultarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTConsultarMatriculaActionPerformed
        consultar();
        listarTabela();
    }//GEN-LAST:event_BTConsultarMatriculaActionPerformed

    private void BTLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTLimparActionPerformed
        limpar();
    }//GEN-LAST:event_BTLimparActionPerformed

    private void BTConsultarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTConsultarSalaActionPerformed
        Jan4.getJan4().setVisible(true);
    }//GEN-LAST:event_BTConsultarSalaActionPerformed

    public void listarTabela(){
        
        DefaultTableModel modelo = (DefaultTableModel)tabCadAlu.getModel();
        modelo.setRowCount(0);
        int posLin = 0;
        
        for(Aluno alu1 :gerAlu.getBdAlu()){
            modelo.insertRow(posLin, new Object[]{alu1.getNome(),alu1.getDataN(),alu1.getEmail(),alu1.getEscolaridade(),alu1.getCpf(),alu1.getDinicio(),alu1.getDfim()});
            posLin++;
        }
    }
    
    public void limpar(){
        txtNome.setText("");
        txtNascimento.setText("");
        txtEmail.setText("");
        txtEscolaridade.setText("");
        txtCPF.setText("");
        txtDIM.setText("");
        txtDFM.setText(""); 
        txtNome.requestFocus();
    }
    
    public void cadastrar(){
        alu = new Aluno();
        
        alu.setNome(txtNome.getText());
        alu.setDataN(Integer.parseInt(txtNascimento.getText()));
        alu.setEmail(txtEmail.getText());
        alu.setEscolaridade(txtEscolaridade.getText());
        alu.setCpf(Integer.parseInt(txtCPF.getText()));
        alu.setDinicio(txtDIM.getText());
        alu.setDfim(txtDFM.getText());
        
        alu = gerAlu.cadAlu(alu);
        
        if(alu == null){
            JOptionPane.showMessageDialog(null, "Já existe um aluno cadastrado com esse CPF", "Erro de cadastro", 0);
        }
        else{
            JOptionPane.showMessageDialog(null, "Aluno cadastrado com sucesso", "Cadastramento de aluno", 0);
        }
    }
    
    public void consultar(){
        alu = new Aluno();
        
        alu.setCpf(Integer.parseInt(txtCPF.getText()));
        
        alu = gerAlu.consAluCpf(alu);
        
        if(alu == null){
            JOptionPane.showMessageDialog(null, "Não existe um aluno cadastrado com esse CPF: "+txtCPF.getText(), "Erro de consulta", 0);
            limpar();
        }
        else{
            txtNome.setText(alu.getNome());
            txtNascimento.setText(Integer.toString(alu.getDataN()));
            txtEmail.setText(alu.getEmail());
            txtEscolaridade.setText(alu.getEscolaridade());
            txtCPF.setText(Integer.toString(alu.getCpf()));
            txtDIM.setText(alu.getDinicio());
            txtDFM.setText(alu.getDfim());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                getJan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BTCadAluno;
    private javax.swing.JButton BTConsultarMatricula;
    private javax.swing.JButton BTConsultarSala;
    private javax.swing.JButton BTFecJan2;
    private javax.swing.JButton BTLimpar;
    private javax.swing.JButton BTMatricular;
    private javax.swing.JLabel RTCPF;
    private javax.swing.JLabel RTDFM;
    private javax.swing.JLabel RTDIM;
    private javax.swing.JLabel RTEmail;
    private javax.swing.JLabel RTEscolaridade;
    private javax.swing.JLabel RTNascimento;
    private javax.swing.JLabel RTNome1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabCadAlu;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtDFM;
    private javax.swing.JTextField txtDIM;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEscolaridade;
    private javax.swing.JTextField txtNascimento;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
