//Rafael Duarte Daltio - 2266539
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Jan3 extends javax.swing.JFrame {
    private GerProf gerProf = new GerProf();
    private Professor prof = new Professor();
    
    private static Jan3 jan3Unico;
    
    private Jan3() {
        initComponents();
    }
    
    public static Jan3 getJan3(){
        if(jan3Unico == null){
            jan3Unico = new Jan3();
        }
        return jan3Unico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RTSiape = new javax.swing.JLabel();
        BTCadProf = new javax.swing.JLabel();
        RTDisciplina = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabCadProf = new javax.swing.JTable();
        BTFecJan3 = new javax.swing.JButton();
        txtDisciplina = new javax.swing.JTextField();
        RTNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        RTDataN = new javax.swing.JLabel();
        txtDataN = new javax.swing.JTextField();
        BTLimpar = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        BTCadastrar = new javax.swing.JButton();
        RTEmail = new javax.swing.JLabel();
        BTConsultar = new javax.swing.JButton();
        txtSiape = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RTSiape.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RTSiape.setText("Siape:");

        BTCadProf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BTCadProf.setText("Cadastro de professor");

        RTDisciplina.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RTDisciplina.setText("Disciplina:");

        tabCadProf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data de nascimento", "Email", "Siape", "Disciplina"
            }
        ));
        jScrollPane3.setViewportView(tabCadProf);

        BTFecJan3.setText("Fechar");
        BTFecJan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTFecJan3ActionPerformed(evt);
            }
        });

        RTNome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RTNome.setText("Nome:");

        RTDataN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RTDataN.setText("Data de nascimento:");

        BTLimpar.setText("Limpar");
        BTLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTLimparActionPerformed(evt);
            }
        });

        BTCadastrar.setText("Cadastrar");
        BTCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTCadastrarActionPerformed(evt);
            }
        });

        RTEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RTEmail.setText("Email:");

        BTConsultar.setText("Consultar");
        BTConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTConsultarActionPerformed(evt);
            }
        });

        txtSiape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSiapeActionPerformed(evt);
            }
        });

        jButton1.setText("Continuar para salas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(596, 596, 596)
                .addComponent(BTCadProf)
                .addGap(0, 596, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RTEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RTSiape)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSiape, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RTDisciplina)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RTDataN)
                                    .addComponent(RTNome))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDataN, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(140, 140, 140)
                        .addComponent(jScrollPane3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BTCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BTConsultar))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTFecJan3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(BTCadProf)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RTNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDataN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RTDataN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RTEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RTSiape)
                            .addComponent(txtSiape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RTDisciplina)
                            .addComponent(txtDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTLimpar)
                    .addComponent(BTCadastrar)
                    .addComponent(BTConsultar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(BTFecJan3))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTFecJan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTFecJan3ActionPerformed
        dispose();
    }//GEN-LAST:event_BTFecJan3ActionPerformed

    private void BTLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTLimparActionPerformed
        limpar();
    }//GEN-LAST:event_BTLimparActionPerformed

    private void BTCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTCadastrarActionPerformed
        cadastrar();
        listarTabela();
        limpar();
    }//GEN-LAST:event_BTCadastrarActionPerformed

    private void BTConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTConsultarActionPerformed
        consultar();
    }//GEN-LAST:event_BTConsultarActionPerformed

    private void txtSiapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSiapeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSiapeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Jan4.getJan4().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void listarTabela(){
        
        DefaultTableModel modelo = (DefaultTableModel)tabCadProf.getModel();
        modelo.setRowCount(0);
        int posLin = 0;
        
        for(Professor prof1 :gerProf.getBdProf()){
            modelo.insertRow(posLin, new Object[]{prof1.getNome(),prof1.getDataN(),prof1.getEmail(),prof1.getSiape(),prof1.getDisciplina()});
            posLin++;
        }
    }
    
    public void limpar(){
        txtNome.setText("");
        txtDataN.setText("");
        txtEmail.setText("");
        txtSiape.setText("");
        txtDisciplina.setText("");
        txtNome.requestFocus();
    }
    
    public void cadastrar(){
        prof = new Professor();
        
        prof.setNome(txtNome.getText());
        prof.setDataN(Integer.parseInt(txtDataN.getText()));
        prof.setEmail(txtEmail.getText());
        prof.setDisciplina(txtDisciplina.getText());
        prof.setSiape(Integer.parseInt(txtSiape.getText()));

        
        prof = gerProf.cadProf(prof);
        
        if(prof == null){
            JOptionPane.showMessageDialog(null, "Já existe um professor cadastrado com esse código", "Erro de cadastro", 0);
        }
        else{
            JOptionPane.showMessageDialog(null, "Professor cadastrado com sucesso", "Cadastramento de professor", 0);
        }
    }
    
    public void consultar(){
        prof = new Professor();
        
        prof.setSiape(Integer.parseInt(txtSiape.getText()));
        
        prof = gerProf.consProfSiape(prof);
        
        if(prof == null){
            JOptionPane.showMessageDialog(null, "Não existe um professor cadastrado com esse código: "+txtSiape.getText(), "Erro de consulta", 0);
            limpar();
        }
        else{
            txtNome.setText(prof.getNome());
            txtDataN.setText(Integer.toString(prof.getDataN()));
            txtEmail.setText(prof.getEmail());
            txtDisciplina.setText(prof.getDisciplina());
            txtSiape.setText(Integer.toString(prof.getSiape()));
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BTCadProf;
    private javax.swing.JButton BTCadastrar;
    private javax.swing.JButton BTConsultar;
    private javax.swing.JButton BTFecJan3;
    private javax.swing.JButton BTLimpar;
    private javax.swing.JLabel RTDataN;
    private javax.swing.JLabel RTDisciplina;
    private javax.swing.JLabel RTEmail;
    private javax.swing.JLabel RTNome;
    private javax.swing.JLabel RTSiape;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabCadProf;
    private javax.swing.JTextField txtDataN;
    private javax.swing.JTextField txtDisciplina;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSiape;
    // End of variables declaration//GEN-END:variables
}
