//Rafael Duarte Daltio - 2266539
public class Principal extends javax.swing.JFrame {
    
    private static Principal princUnico;
    
    private Principal() {
        initComponents();
    }
    
    public static Principal getPrinc(){
        if(princUnico == null){
            princUnico = new Principal();
        }
        return princUnico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTFecJan1 = new javax.swing.JButton();
        BTAluno = new javax.swing.JButton();
        BTProf = new javax.swing.JButton();
        BarMenuPrinc = new javax.swing.JMenuBar();
        MnPrinc = new javax.swing.JMenu();
        LogAluno = new javax.swing.JMenuItem();
        LogProf = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Janela 1");

        BTFecJan1.setText("Fechar");
        BTFecJan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTFecJan1ActionPerformed(evt);
            }
        });

        BTAluno.setText("Login Aluno");
        BTAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTAlunoActionPerformed(evt);
            }
        });

        BTProf.setText("Login Professor");
        BTProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTProfActionPerformed(evt);
            }
        });

        MnPrinc.setText("App de aulas particulares");

        LogAluno.setText("Login aluno");
        LogAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogAlunoActionPerformed(evt);
            }
        });
        MnPrinc.add(LogAluno);

        LogProf.setText("Login professor");
        LogProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogProfActionPerformed(evt);
            }
        });
        MnPrinc.add(LogProf);

        BarMenuPrinc.add(MnPrinc);

        setJMenuBar(BarMenuPrinc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTFecJan1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(BTProf)
                .addGap(60, 60, 60)
                .addComponent(BTAluno)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTProf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(BTFecJan1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTFecJan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTFecJan1ActionPerformed
        dispose();
    }//GEN-LAST:event_BTFecJan1ActionPerformed

    private void LogAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogAlunoActionPerformed
        Jan2.getJan2().setVisible(true);
    }//GEN-LAST:event_LogAlunoActionPerformed

    private void BTAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTAlunoActionPerformed
        Jan2.getJan2().setVisible(true);
    }//GEN-LAST:event_BTAlunoActionPerformed

    private void BTProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTProfActionPerformed
        Jan3.getJan3().setVisible(true);
    }//GEN-LAST:event_BTProfActionPerformed

    private void LogProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogProfActionPerformed
        Jan3.getJan3().setVisible(true);
    }//GEN-LAST:event_LogProfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                getPrinc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTAluno;
    private javax.swing.JButton BTFecJan1;
    private javax.swing.JButton BTProf;
    private javax.swing.JMenuBar BarMenuPrinc;
    private javax.swing.JMenuItem LogAluno;
    private javax.swing.JMenuItem LogProf;
    private javax.swing.JMenu MnPrinc;
    // End of variables declaration//GEN-END:variables
}
